### PR TITLE
Large file support

### LINKED ISSUE #11: Files >2GB don't work due to 32bit truncation
Open_Buffer_Continue_GoTo_Get() returns a 64bit seek position, but the binding to JS makes a long (32bit) out of it. Thus seeking in large files doesn't work.  It gets obviuos when comparing the offsets from JS and native code:

native:
lseek(4, 2131533686, SEEK_SET)
lseek(4, 4261375884, SEEK_SET)

JS:
offset 2130943862 state 5 seekto -33591412

4261375884 is -33591412 as int32_t ;)

BTW: I tried to fix that on my own in the binding, but emscripten seems to have long term troubles under Ubuntu. Can you give an example of a "proven" build system? Thanks...

### PR DESCRIPTION
**Pull request by TannerRogalsky**
This resolves #11.

I really just followed the solution in that issue.

A PR to update the gh-pages branch with the small API change will follow.

### CODE REVIEW

File: mediainfojs.cpp [hunk 1]
```diff
@@ -18,15 +18,29 @@ class MediaInfoJs {
   int open_buffer_continue(const std::string& data, double size) {
     return mi.Open_Buffer_Continue((ZenLib::int8u*)data.data(), (ZenLib::int64u)size);
   }
-  long open_buffer_continue_goto_get(){
-    return (int64_t)mi.Open_Buffer_Continue_GoTo_Get();
+  int open_buffer_continue_goto_get(){
+    seekTo.total = mi.Open_Buffer_Continue_GoTo_Get();
+    return seekTo.lower;
+  }
+  int get_seek_to_upper() {
```
Comment (JeromeMartinez) [inline mediainfojs.cpp]: I recommend `open_buffer_continue_goto_get_high` in order to better see the relation with the low version.
The low version could be called `open_buffer_continue_goto_get_low` as it breaks the expect behavior (a 64-bit integer) from upstream `open_buffer_continue_goto_get`
`open_buffer_continue_goto_get` code could be kept for legacy reasons.

File: mediainfojs.cpp [hunk 2]
```diff
@@ -18,15 +18,29 @@ class MediaInfoJs {
...
   }
   void close() {
     mi.Close();
   }
+private:
+  union SeekTo {
+    int64_t total;
+    struct {
+      int32_t lower;
+      int32_t upper;
```
Comment (JeromeMartinez) [inline mediainfojs.cpp]: I recommend `low` and `high`, more classic (and actually you use these words in the other PR about doc).

File: mediainfojs.cpp (hunk 1 above)
Comment (TannerRogalsky) [reply mediainfojs.cpp]: @JeromeMartinez Would `open_buffer_continue_goto_get_high` also invoke `Open_Buffer_Continue_GoTo_Get`? The name infers that it should but I'm not sure if that's correct or what the implication of that behaviour is.

File: mediainfojs.cpp (hunk 2 above)
Comment (TannerRogalsky) [reply mediainfojs.cpp]: Fair enough. I will change that.

File: mediainfojs.cpp (hunk 1 above)
Comment (JeromeMartinez) [reply mediainfojs.cpp]: Good catch.
Now I recommend, if it is possible on the glue side (I did not test), to remove the struct and call C `Open_Buffer_Continue_GoTo_Get()` call for both low and high request, it would avoid the intermediate value which may be dangerous (depending on which order is used for getting high or low value).

`Open_Buffer_Continue_GoTo_Get()` can be called several times, it returns (very quickly) the same value until a parsing call is made.

**Comment by TannerRogalsky** [comment]
@JeromeMartinez Thanks for you feedback! If you could review this most recent set of changes.

**Comment by JeromeMartinez** [comment]
No other remark on my side.
